QINIU_AK = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
QINIU_SK = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
QINIU_BUCKET = 'xxxx'
QINIU_DOMAIN = 'http://xxx.xxx.clouddn.com/'
TMP_FILE_NAME = './tmp/clipboard.jpg'
LINK_TYPE = 'markdown'
